import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "./components/header";
import "./styles/globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${roboto.variable} antialiased`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
